cmake_minimum_required(VERSION 3.10)

# same with Flutter Engine building option
add_definitions(
  -DRAPIDJSON_HAS_STDSTRING
  -DRAPIDJSON_HAS_CXX11_RANGE_FOR
  -DRAPIDJSON_HAS_CXX11_RVALUE_REFS
  -DRAPIDJSON_HAS_CXX11_TYPETRAITS
  -DRAPIDJSON_HAS_CXX11_NOEXCEPT
)
